<template>
	<app-page title="F.A.Q.">
		<h1>FAQ</h1>
		<div class="accordion">
			<div class="accordion__title title" @click="isOpenAbout = !isOpenAbout">
				What is&nbsp;this site about?
			</div>
			<div class="accordion__body" v-if="isOpenAbout">
				<div class="accordion__text">
					<p>
						This mini web-app is&nbsp;created for true lovers of&nbsp;music and
						music festivals!
					</p>
					<p>
						On&nbsp;the main page you can look at&nbsp;the greatest festivals
						in&nbsp;the world that, unfortunately, never existed.
					</p>
					<p>
						You can also create your own festival by&nbsp;choosing the name,
						date and place, different artists and even choose your own cover!
					</p>
					<p>
						Add festivals to&nbsp;your list and on&nbsp;the page
						<router-link to="/my-fests" class="link">My fests</router-link>
						look only at&nbsp;them. Or&nbsp;you can refresh all the data and
						start all over again!
					</p>
				</div>
				<div class="accordion__pic accordion__pic--1"></div>
			</div>
		</div>
		<div class="accordion">
			<div class="accordion__title title" @click="isOpenCatch = !isOpenCatch">
				What&rsquo;s the catch of&nbsp;this website?
			</div>
			<div class="accordion__body" v-if="isOpenCatch">
				<div class="accordion__pic accordion__pic--4"></div>
				<div class="accordion__text">
					<p>
						The main feature of&nbsp;this website is&nbsp;that it&nbsp;generates
						maximum random data with minimal input.
					</p>

					<p>
						I&nbsp;have prepared a&nbsp;small database with names, bands,
						genres, as&nbsp;well as&nbsp;uploaded various fonts and photos.
						Based on&nbsp;this data, my&nbsp;script generates different
						festivals with completely random data from this database and mixes
						them with other data from third-party libraries.
					</p>

					<p>
						Each time, absolutely everything is&nbsp;shuffled for any
						user&nbsp;&mdash; cities, groups, genres, dates, covers... And
						my&nbsp;favorite feature is&nbsp;that each group on&nbsp;the
						festival page has its own random font based on&nbsp;its genre, and
						the headliner also has a&nbsp;random decorative element.
					</p>

					<p>
						Due to&nbsp;the large number of&nbsp;different rules that&nbsp;I
						came up&nbsp;with and implemented for generating, it&nbsp;becomes
						a&nbsp;kind of&nbsp;game element, and&nbsp;I hope that users will
						want to&nbsp;stay on&nbsp;the site longer :)
					</p>
				</div>
			</div>
		</div>
		<div class="accordion">
			<div class="accordion__title title" @click="isOpenHow = !isOpenHow">
				How was it&nbsp;developed?
			</div>
			<div class="accordion__body" v-if="isOpenHow">
				<div class="accordion__text">
					<p>
						I&nbsp;have prepared the following data: names, list of&nbsp;bands
						and genres. This small database is&nbsp;hosted on&nbsp;<a
							class="link"
							target="_blank"
							href="https://firebase.google.com/"
							>Google Firebase</a
						>. Different fonts and pictures are in&nbsp;the project itself
					</p>
					<p>
						Everything else is&nbsp;generated by&nbsp;the script (for example,
						random dates of&nbsp;festivals) or&nbsp;taken from third-party
						libraries. For example, I&nbsp;took a&nbsp;list of&nbsp;all
						countries, cities and their geographic data for Google maps from
						<a
							class="link"
							target="_blank"
							href="https://www.npmjs.com/package/country-state-city"
							>country-state-city</a
						>. Unfortunately, this library doesn't have the most accurate data
						on&nbsp;the longitude and latitude of&nbsp;cities, so&nbsp;sometimes
						Google maps on&nbsp;the festival page shows inaccurate location, but
						in&nbsp;most cases everything is&nbsp;correct.
					</p>

					<ul class="list">
						<li class="list__item">
							<span class="field">Basis:</span> Vue (composition API) with
							vue-router and vuex
						</li>
						<li class="list__item">
							<span class="field">Bundler:</span> Vue CLI
						</li>
						<li class="list__item"><span class="field">Styles:</span> SASS</li>
						<li class="list__item">
							<span class="field">Requests:</span> Axios
						</li>
						<li class="list__item">
							<span class="field">Database and hosting: </span>
							<a
								class="link"
								target="_blank"
								href="https://firebase.google.com/"
								>Google Firebase</a
							>
						</li>
						<li class="list__item">
							<span class="field">Fonts: </span>
							<a class="link" target="_blank" href="https://fonts.google.com/"
								>Google fonts</a
							>
						</li>
						<li class="list__item">
							<span class="field">Images: </span>
							<a class="link" target="_blank" href="https://unsplash.com/"
								>Unsplash</a
							>
						</li>
						<li class="list__item">
							<span class="field">Icons: </span>
							<a class="link" target="_blank" href="https://www.svgrepo.com/"
								>SVG Repo</a
							>
						</li>
					</ul>
				</div>
				<div class="accordion__pic accordion__pic--13"></div>
			</div>
		</div>
		<div class="accordion">
			<div class="accordion__title title" @click="isOpenAuthor = !isOpenAuthor">
				Who is&nbsp;author?
			</div>
			<div class="accordion__body" v-if="isOpenAuthor">
				<div class="accordion__pic accordion__pic--3"></div>
				<div class="accordion__text">
					<p>
						All idea, design and code belongs to&nbsp;me,
						<span class="author">Egor Arkharov.</span>
					</p>
					<p>
						My&nbsp;contacts you can see
						<a class="link" href="#" @click.prevent="open">here</a>.
					</p>
					<p>
						Github of this project
						<a
							class="link"
							target="_blank"
							href="https://github.com/Egor-arkharov/myfests"
							>here</a
						>.
					</p>
				</div>
			</div>
		</div>
	</app-page>
</template>

<script>
import { ref } from "vue";
import { useStore } from "vuex";
import AppPage from "../components/ui/App/AppPage.vue";

export default {
	setup() {
		const store = useStore();

		return {
			isOpenAbout: ref(false),
			isOpenCatch: ref(false),
			isOpenHow: ref(false),
			isOpenAuthor: ref(false),
			open: () => store.commit("settings/openSidebar"),
		};
	},
	components: {
		AppPage,
	},
};
</script>

<style lang="scss" scoped>
h1 {
	text-align: center;
	margin-bottom: 30px;
}

.accordion {
	width: 80%;
	margin: 0 auto 15px;

	color: $black-color;
	border: 1px solid $main-color;
	border-radius: 10px;

	&:last-child {
		margin-bottom: 0;
	}

	&__title,
	&__body {
		padding: 10px 20px;
	}

	&__title {
		position: relative;
		@include font-xxl;
		cursor: pointer;

		@include hover {
			color: $main-color;
		}
	}

	&__body {
		display: flex;
		justify-content: space-between;

		font-family: $main-font;
		margin-top: 25px;
	}

	&__text {
		font-size: 20px;
		line-height: 24px;

		display: flex;
		flex-direction: column;
		justify-content: space-around;

		width: 60%;
	}

	&__subtext {
		margin: 20px 0 10px;
	}

	&__pic {
		width: 35%;
		min-height: 250px;
		background-color: lighten($grey-color, 20%);
		background-repeat: no-repeat;
		background-position: center;
		background-size: cover;

		&--1 {
			background-image: url("@/assets/images/fests/img-1.jpg");
		}

		&--4 {
			background-image: url("@/assets/images/fests/img-4.jpg");
		}

		&--13 {
			background-image: url("@/assets/images/fests/img-13.jpg");
		}

		&--3 {
			background-image: url("@/assets/images/fests/img-3.jpg");
		}
	}
}

.field {
	font-family: $main-font-bold-ex;
}

.link {
	font-family: $main-font-bold;
	color: $main-color;

	@include hover {
		color: darken($main-color, 20%);
	}
}

.author {
	font-family: $main-font-semibold;
	white-space: nowrap;
}

p:not(:last-child) {
	margin-bottom: 20px;
}

@media (max-width: #{map-get($breakpoints, 'md')}) {
	.accordion {
		width: 100%;

		&__body {
			margin-top: 10px;
			flex-direction: column;
		}

		&__title {
			@include font-xl;
		}

		&__text,
		&__pic {
			width: 100%;
		}

		&__text {
			@include font-m;
		}

		&__pic {
			height: 200px;
			margin-top: 35px;
			order: 1;
		}
	}
}

@media (max-width: #{map-get($breakpoints, 'xs')}) {
	.accordion {
		&__title {
			@include font-xxl;
		}

		&__body {
			margin-top: 5px;
		}
	}
}
</style>
